name: Test the GitHub Action

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare test data
        run: echo 'title = "My New Hugo Site"' > config.toml

      - name: Invoke this action
        uses: ./

      - name: Assert site was built
        run: |
          count=$(find build | wc -l)
          if [ $count -eq 0 ]; then
            exit 1
          else
            echo "Found ${count} files in the build directory:"
            ls -al build
          fi
